name: Protobuf

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'docs/**'
      - 'bindings/**'
      - 'scip.proto'
      - 'buf**'

jobs:
  protoc-gen-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/asdf
        with:
          js: true
          rust: true
          golang: true
      - name: Cache `.bin` folder
        id: cache-setup
        uses: actions/cache@v2
        with:
          path: .bin
          key: ${{ runner.os }}-bin
      - run: ./dev/proto-generate.sh
      - run: git diff --exit-code
